`timescale 1ns / 1ps
// ============================================================================
// AeroLink-8b10b :: CRC-16-CCITT Bytewise Calculator
// Polynomial: x^16 + x^12 + x^5 + 1  (0x1021), Init: 0xFFFF, MSB-first
// ============================================================================

module aerolink_crc16 (
    input  wire        clk,
    input  wire        rst,
    input  wire        init,      // synchronous init to 0xFFFF
    input  wire        valid,     // data_in valid this cycle
    input  wire [7:0]  data_in,
    output wire [15:0] crc_out    // current CRC value
);

    reg [15:0] crc_reg;
    assign crc_out = crc_reg;

    // ----------------------------------------------------------------
    // Bytewise CRC-16-CCITT XOR equations (MSB-first, poly 0x1021)
    // Generated by unrolling 8 serial LFSR iterations.
    // c = crc_reg, d = data_in  (d[7] is MSB, processed first)
    // ----------------------------------------------------------------
    wire [15:0] c;
    wire [7:0]  d;
    wire [15:0] crc_nxt;

    assign c = crc_reg;
    assign d = data_in;

    assign crc_nxt[ 0] = c[ 8] ^ c[12] ^ d[0] ^ d[4];
    assign crc_nxt[ 1] = c[ 9] ^ c[13] ^ d[1] ^ d[5];
    assign crc_nxt[ 2] = c[10] ^ c[14] ^ d[2] ^ d[6];
    assign crc_nxt[ 3] = c[11] ^ c[15] ^ d[3] ^ d[7];
    assign crc_nxt[ 4] = c[12] ^ d[4];
    assign crc_nxt[ 5] = c[ 8] ^ c[12] ^ c[13] ^ d[0] ^ d[4] ^ d[5];
    assign crc_nxt[ 6] = c[ 9] ^ c[13] ^ c[14] ^ d[1] ^ d[5] ^ d[6];
    assign crc_nxt[ 7] = c[10] ^ c[14] ^ c[15] ^ d[2] ^ d[6] ^ d[7];
    assign crc_nxt[ 8] = c[ 0] ^ c[11] ^ c[15] ^ d[3] ^ d[7];
    assign crc_nxt[ 9] = c[ 1] ^ c[12] ^ d[4];
    assign crc_nxt[10] = c[ 2] ^ c[13] ^ d[5];
    assign crc_nxt[11] = c[ 3] ^ c[14] ^ d[6];
    assign crc_nxt[12] = c[ 4] ^ c[ 8] ^ c[12] ^ c[15] ^ d[0] ^ d[4] ^ d[7];
    assign crc_nxt[13] = c[ 5] ^ c[ 9] ^ c[13] ^ d[1] ^ d[5];
    assign crc_nxt[14] = c[ 6] ^ c[10] ^ c[14] ^ d[2] ^ d[6];
    assign crc_nxt[15] = c[ 7] ^ c[11] ^ c[15] ^ d[3] ^ d[7];

    always @(posedge clk) begin
        if (rst) begin
            crc_reg <= 16'hFFFF;
        end else if (init) begin
            crc_reg <= 16'hFFFF;
        end else if (valid) begin
            crc_reg <= crc_nxt;
        end
    end

endmodule
